{% set name = "qibojit" %}
{% set version = "0.0.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/qiboteam/qibojit/archive/v{{ version }}.tar.gz
  sha256: 6229294b8882b3e3356b53a27bd82fbbfbf3510323fbe9945930ead799ccc879

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - numba >=0.51.0
    - psutil
    - python >=3.6

test:
  imports:
    - qibojit
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/qiboteam/qibojit
  summary: Simulation tools based on numba and cupy.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - scarrazza
