{% set name = "qibojit" %}
{% set version = "0.0.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/qiboteam/qibojit/archive/v{{ version }}.tar.gz
  sha256: 224748473c928bfaa89ab1d62607b3c7b6699369b0c9449a395b9aa0b633f35b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - numba >=0.51.0
    - scipy
    - psutil
    - python >=3.7
    - qibo >=0.1.7

test:
  imports:
    - qibojit
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/qiboteam/qibojit
  summary: Simulation tools based on numba and cupy.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - scarrazza
