{% set name = "qibojit" %}
{% set version = "0.0.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/qiboteam/qibojit/archive/v{{ version }}.tar.gz
  sha256: 0cc74e60acb7aeb1e627054098389435dd509439c1e2188b70f6e97e68a6ce85

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - numba >=0.51.0
    - scipy
    - psutil
    - python >=3.8
    - qibo >=0.1.11

test:
  imports:
    - qibojit
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/qiboteam/qibojit
  summary: Simulation tools based on numba and cupy.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - scarrazza
