{% set name = "qibojit" %}
{% set version = "0.0.10" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/qiboteam/qibojit/archive/v{{ version }}.tar.gz
  sha256: 8aab25cd03de80a86aef010c42e590381407da6ee12b3bc19132b137c493a2ba

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - numba >=0.51.0
    - scipy
    - psutil
    - python >=3.8
    - qibo >=0.1.13

test:
  imports:
    - qibojit
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/qiboteam/qibojit
  summary: Simulation tools based on numba and cupy.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - scarrazza
